### ISSUE TITLE
SubprocessWorkflow bug with ZMQServer in force_wfmanager

### ISSUE THREAD

**Issue by flongford** [force-h2020/force-bdss-plugin-enthought-example#51]
The serialization methods on `SubprocessWorkflow` currently seem incompatible with the `force_wfmanager`'s `ZMQServer`.

Running the `ExampleMCO` class causes the output in the log:

```
ERROR:force_wfmanager.server.zmq_server:Unknown request received ['HELLO', '', '1']
ERROR:force_wfmanager.server.zmq_server:Unable to retrieve data
Traceback (most recent call last):
  File "/Users/flongford/FORCE/force-wfmanager/force_wfmanager/server/zmq_server.py", line 146, in run
    data = [x.decode("utf-8") for x in socket.recv_multipart()]
  File "/Users/flongford/.edm/envs/force-py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 395, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7288)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7086)
  File "zmq/backend/cython/socket.pyx", line 150, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2131)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2038)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7916)
zmq.error.ZMQError: Operation cannot be accomplished in current state
```

**Comment by flongford** [comment]
I believe this could be because the `SubprocessWorfklow` will create a new workflow JSON containing the same `notification_listeners` when spawning a new subprocess to run the BDSS.

Therefore we probably end up with duplicated messages being sent to and from the `WfManager`, causing race conditions.
